name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: New Version (e.i. 0.0.0)
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Update version file
        run: echo "${{ github.event.inputs.version }}" > VERSION
      - name: Commit version file
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated version update to ${{ github.event.inputs.version }}"
      - name: Example variable usage
        run: git tag ${{ github.event.inputs.version }}
      - name: Push all
        run: |
          git status
          git log --raw
          git push