name: Publish

on:
  release:
    types:
      - created
#  workflow_run:
#    workflows: ["Bump Version"]
#    types: [completed]
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*.*.*' # i.e. v1.0.0, v20.15.10
#      - '*.*.*' # i.e. 1.0.0, 20.15.10

jobs:
  update-verstion-and-chengelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Update version file
      run: |
        cat VERSION
        echo "VERSION ${{ github.ref_name }}"
        echo -n "${{ github.ref_name }}" > VERSION
    - name: Update changelog file
      run: |
        echo "CHANGELOG"
    - name: Commit updated files
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout origin master
        git add VERSION
        git commit -m "Automated version update to ${{ github.event.inputs.version }}"
        git push origin
    - name: Tag new commit
      run: |
        git tag --force ${{ github.ref_name }}
        git push origin ${{ github.ref_name }} --force

  update-release-github:
    needs: update-verstion-and-chengelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Release rescription
        run: |
          echo "CHANGELOG"

  release-python-package:
    needs: update-verstion-and-chengelog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build python package
      run: |
        python -m pip install wheel twine
        python -m pip wheel . --no-deps --wheel-dir dist
        twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*

  release-github-pages:
    needs: update-verstion-and-chengelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-3.9-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'setup.cfg') }}-docs
          restore-keys: |
            ${{ runner.os }}-python-3.9-
            ${{ runner.os }}-python-
            ${{ runner.os }}-
      - name: Install dependencies
        run: python -m pip install -e .[docs]
      - name: Build and publish docs
        run: |
          git fetch --all
          # lazydocs
          python -m mkdocs build --config-file docs/mkdocs.yml
          python -m mkdocs gh-deploy --config-file docs/mkdocs.yml --force
